---
driver:
  name: vagrant
  use_sudo: false
  network:
    - ["forwarded_port", {guest: 7990, host: 7990}]
    - ["forwarded_port", {guest: 7999, host: 7999}]
    - ["forwarded_port", {guest: 7992, host: 7992}]
    - ["forwarded_port", {guest: 7993, host: 7993}]
  vm_hostname: "default-centos-72.vagrantup.com"
  customize:
    memory: 2048
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-6.9
#  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[java]
      - recipe[git::source]
      - recipe[test::default]
      - recipe[test::backup_client]
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/smoke/default/backup_client_test.rb 
    attributes:
      java:
        install_flavor: 'oracle'
        jdk_version: '8'
        java_home: "/usr/lib/jvm/java-8-oracle"
        oracle:
          accept_oracle_download_terms: true
      git:
        version: '2.8.1'
      bitbucket:
        properties: {"setup.displayName":           "MyBitbucket",
                     "setup.baseUrl":               "http://localhost:7990",
                     "setup.license":               "my license",
                     "setup.sysadmin.username":     "admin",
                     "setup.sysadmin.password":     "adminpwd",
                     "setup.sysadmin.displayName":  "admin",
                     "setup.sysadmin.emailAddress": "myemail@gmail.com"}
