driver:
  name: dokken
  privileged: true 
  chef_version: current
  forward:
  - 7990:7990
  - 7992:7992
  - 7993:7993
  - 7999:7999
  memory: 2048

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

platforms:
- name: centos-6
  driver:
    image: centos:6
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install lsof which initscripts net-tools wget

- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN yum -y install which initscripts net-tools wget curl
