sudo: false

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

services: docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install vagrant

install:
  - chef exec bundle install
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
#  - /opt/chefdk/bin/chef exec bundle exec berks install

script:
  - chef exec bundle exec rake style
  - chef exec bundle exec rake unit
  - KITCHEN_LOCAL_YAML=./.kitchen.dokken.yml chef exec kitchen test
