sudo: false

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

services: docker

install:
  - chef exec bundle install
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
#  - /opt/chefdk/bin/chef exec bundle exec berks install

script:
#  - chef exec rspec
  - KITCHEN_LOCAL_YAML=./.kitchen.dokken.yml chef exec kitchen test
