sudo: false
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
install: echo "skip bundle install"
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
#  - /opt/chefdk/bin/chef exec bundle exec berks install
script:
  - /opt/chefdk/bin/chef exec rspec
